# Generated by Django 5.2.6 on 2025-09-10 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_tags_questions_answers_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='questions', to='app.tags'),
        ),
    ]
