# Generated by Django 5.2.6 on 2025-09-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_questions_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='value',
            field=models.SmallIntegerField(choices=[(1, 'upvote'), (-1, 'downvote')]),
        ),
    ]
