# Generated by Django 5.2.6 on 2025-09-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_tags_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questions',
            options={'ordering': ['-posted_at']},
        ),
    ]
